version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 6
  method-count:
    enabled: false
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
    config:
      threshold: 40 # minimum "mass" a code block must have to be analyzed
  identical-code:
    config:
      threshold: 40 # minimum "mass" a code block must have to be analyzed
plugins:
  checkstyle:
    enabled: true
    config:
      file: "quality/checkstyle.xml"
  duplication: # https://github.com/codeclimate/codeclimate-duplication
    enabled: true
    config:
      count_threshold: 5 # minimum duplications to show in report
exclude_patterns:
  - src/main/resources/
  - build/
  - charts/
  - ci/
  - gradle/
  - quality/
  - src/test/
