image: mtr.devops.telekom.de/cof/worker:1.10-java17

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  VERSION: 0.0.1-$CI_COMMIT_SHORT_SHA
  ENABLE_CODE_QUALITY: "true"
  DS_JAVA_VERSION: 17
  DOCKER_IMAGE_VERSION: 0.1-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_EXPIRES: 3d
  DOCKER_IMAGE_NAME: doit2day-service
  DOCKER_REGISTRY_URL: mtr.devops.telekom.de
  DOCKER_REGISTRY_BASE_GROUP: cof
  DOCKER_REGISTRY_TARGET_GROUP: ((YOUR IMAGE LOCATION GROUP))
  DOCKER_REGISTRY_BASE_IMAGE: azuljre:17.34.20-alpine-3.16.0
  APPLICATION: doit2day-service

include:
  - local: 'ci/build.yml'
  - local: 'ci/code-quality.yml'

stages:
  - build
  - check
